# Generated by Django 4.2.4 on 2023-08-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название товара')),
                ('amount', models.IntegerField(max_length=6, verbose_name='Цена товара')),
                ('description', models.TextField()),
            ],
        ),
    ]
