# Generated by Django 4.2.6 on 2023-10-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, verbose_name='Короткая метка'),
        ),
    ]
