# Generated by Django 4.2.6 on 2023-11-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_category_slug_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.TextField(default='Лапша: пшеничная мука, пальмовое масло, крахмал тапиоки, соль, сахар, рыбный соус, усилитель вкуса (621), эмульгатор (466), стабилизатор (451(i), 501(i)), разрыхлитель (500(ii)) , натуральный краситель куркумин, порошок куркумы, антиоксиданты (320, 321). Пакеты специй: экстракт тамаринда, пальмовое масло, соль, сахар, креветки 19,8 г/кг, усилители вкуса (621, 631, 627, 364(ii), 951), специи (чили, лук, лемонграсс, калган, имбирь), сушеные. зеленый лук, сушеный фиолетовый лук, регулятор кислотности (330), сушеный кориандр, рыбный соус, синтетический ароматизатор лимона, тапиоковый крахмал, натуральный краситель (олеорезин паприки, куркумин). В составе: пшеничная мука, креветки, рыба.', verbose_name='Ингридиенты'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=255, verbose_name='Короткая метка'),
        ),
    ]
