# Generated by Django 4.2.6 on 2024-01-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='taste',
            field=models.CharField(blank=True, max_length=255, verbose_name='Краткое описание вкуса лапши'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='product_images'),
        ),
    ]
