# Generated by Django 5.0a1 on 2023-09-28 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_question_is_published_question_update_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['-pub_date']},
        ),
        migrations.AddField(
            model_name='question',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['-pub_date'], name='polls_quest_pub_dat_ca81de_idx'),
        ),
    ]
