# Generated by Django 5.0a1 on 2023-09-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_alter_question_options_question_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='slug',
            field=models.SlugField(default='', unique=True),
        ),
    ]
