# Generated by Django 5.0a1 on 2023-09-30 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_alter_question_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=1),
        ),
    ]
